sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t psychonaut/rust-nightly .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push psychonaut/rust-nightly
