on:
  push:
  schedule:
    - cron: '0 22 * * *'

name: General checks
jobs:
  build:
    name: push:deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: psychonaut/rust-nightly
          tags: latest,$(date '+%Y-%m-%d')
